package generator;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeVariableName;
import io.vavr.Tuple2;
import java.io.File;
import java.io.IOException;
import javax.lang.model.element.Modifier;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

import static generator.utils.Initializer.initMapper;

/**
 * @author Ruslan Sennov, Grzegorz Piwowarek</a>
 */
public class BindingClass {

    public static void generate(java.util.Map<Class<?>, Tuple2<String, String>> cases1, java.util.Map<Class<?>, Tuple2<String, String>> cases2) throws IOException {

        TypeSpec.Builder pojoTest = TypeSpec.classBuilder("BindingClassTest")
            .addJavadoc("generated by {@link generator.Generator} - don't edit manually\n")
            .addModifiers(Modifier.PUBLIC);
        initMapper(pojoTest, "MAPPER");

        pojoTest.addType(TypeSpec.interfaceBuilder("MyInterface")
            .addModifiers(Modifier.PUBLIC)
            .addTypeVariable(TypeVariableName.get("T"))
            .addAnnotation(AnnotationSpec.builder(JsonTypeInfo.class)
                .addMember("use", "$T.CLASS", JsonTypeInfo.Id.class)
                .addMember("include", "$T.PROPERTY", JsonTypeInfo.As.class)
                .addMember("property", "$S", "@class")
                .build())
            .addAnnotation(AnnotationSpec.builder(JsonAutoDetect.class)
                .addMember("fieldVisibility", "$T.ANY", JsonAutoDetect.Visibility.class)
                .addMember("getterVisibility", "$T.NONE", JsonAutoDetect.Visibility.class)
                .addMember("setterVisibility", "$T.NONE", JsonAutoDetect.Visibility.class)
                .build())
            .addMethod(MethodSpec.methodBuilder("myMethod")
                .addModifiers(Modifier.ABSTRACT, Modifier.PUBLIC)
                .addParameter(ParameterSpec.builder(TypeVariableName.get("T"), "value").build())
                .returns(TypeName.BOOLEAN)
                .build())
            .build());
        pojoTest.addType(TypeSpec.classBuilder("ImplementedClass")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addSuperinterface(ParameterizedTypeName.get(ClassName.get("", "MyInterface"), ClassName.get(Integer.class)))
            .addMethod(MethodSpec.methodBuilder("myMethod")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(ParameterSpec.builder(ClassName.get(Integer.class), "value").build())
                .returns(TypeName.BOOLEAN)
                .addStatement("return false")
                .build())
            .build());
        cases1.forEach((k, v) -> addCase1(pojoTest, k, v));
        cases2.forEach((k, v) -> addCase2(pojoTest, k, v));

        JavaFile javaFile = JavaFile.builder("io.vavr.jackson.generated", pojoTest.build())
            .indent("    ")
            .skipJavaLangImports(true)
            .build();

        javaFile.writeTo(new File("src/test/java"));
    }

    private static void addCase1(TypeSpec.Builder builder, Class<?> clz, Tuple2<String, String> m) {
        MethodSpec.Builder testBuilder = MethodSpec.methodBuilder("shouldHandle" + clz.getSimpleName() + "Class").addAnnotation(Test.class);
        MethodSpec testSpec = testBuilder
            .addStatement("$L src = new $L(" + m._1 + ")", clz.getSimpleName() + "Class", clz.getSimpleName() + "Class")
            .addStatement("var json = MAPPER.writeValueAsString(src)")
            .addStatement("$L restored = MAPPER.readValue(json, $L.class)", clz.getSimpleName() + "Class", clz.getSimpleName() + "Class")
            .addStatement("$T.assertThat(restored.value.$L).isInstanceOf($L)", ClassName.get(Assertions.class), m._2, "ImplementedClass.class")
            .build();

        builder.addMethod(testSpec);
        TypeName valueTypeName = ParameterizedTypeName.get(ClassName.get(clz),
            ParameterizedTypeName.get(ClassName.get("", "MyInterface"), ClassName.get(Integer.class)));
        builder.addType(TypeSpec.classBuilder(clz.getSimpleName() + "Class")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addField(FieldSpec.builder(valueTypeName, "value", Modifier.FINAL)
                .addAnnotation(AnnotationSpec.builder(JsonProperty.class).addMember("value", "$S", "value").build())
                .build())
            .addMethod(MethodSpec.constructorBuilder()
                .addParameter(ParameterSpec.builder(valueTypeName, "value")
                    .addAnnotation(AnnotationSpec.builder(JsonProperty.class).addMember("value", "$S", "value").build())
                    .build())
                .addStatement("this.value = value")
                .build())
            .build());
    }

    private static void addCase2(TypeSpec.Builder builder, Class<?> clz, Tuple2<String, String> m) {
        MethodSpec.Builder testBuilder = MethodSpec.methodBuilder("shouldHandle" + clz.getSimpleName() + "Class")
            .addAnnotation(Test.class);
        MethodSpec testSpec = testBuilder
            .addStatement("$L src = new $L(" + m._1 + ")", clz.getSimpleName() + "Class", clz.getSimpleName() + "Class")
            .addStatement("var json = MAPPER.writeValueAsString(src)")
            .addStatement("$L restored = MAPPER.readValue(json, $L.class)", clz.getSimpleName() + "Class", clz.getSimpleName() + "Class")
            .addStatement("$T.assertThat(restored.value.$L).isInstanceOf($L)", ClassName.get(Assertions.class), m._2, "ImplementedClass.class")
            .build();

        builder.addMethod(testSpec);
        TypeName valueTypeName = ParameterizedTypeName.get(ClassName.get(clz), ClassName.get(Integer.class),
            ParameterizedTypeName.get(ClassName.get("", "MyInterface"), ClassName.get(Integer.class)));
        builder.addType(TypeSpec.classBuilder(clz.getSimpleName() + "Class")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addField(FieldSpec.builder(valueTypeName, "value", Modifier.FINAL)
                .addAnnotation(AnnotationSpec.builder(JsonProperty.class).addMember("value", "$S", "value").build())
                .build())
            .addMethod(MethodSpec.constructorBuilder()
                .addParameter(ParameterSpec.builder(valueTypeName, "value")
                    .addAnnotation(AnnotationSpec.builder(JsonProperty.class).addMember("value", "$S", "value").build())
                    .build())
                .addStatement("this.value = value")
                .build())
            .build());
    }
}
